// Code generated by MockGen. DO NOT EDIT.
// Source: data/interfaces/interfaces.go

package mock_interfaces

import (
	gomock "github.com/golang/mock/gomock"
	domain "kudos/domain"
	errs "kudos/domain/errs"
	reflect "reflect"
)

// MockIPersonRepository is a mock of IPersonRepository interface
type MockIPersonRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPersonRepositoryMockRecorder
}

// MockIPersonRepositoryMockRecorder is the mock recorder for MockIPersonRepository
type MockIPersonRepositoryMockRecorder struct {
	mock *MockIPersonRepository
}

// NewMockIPersonRepository creates a new mock instance
func NewMockIPersonRepository(ctrl *gomock.Controller) *MockIPersonRepository {
	mock := &MockIPersonRepository{ctrl: ctrl}
	mock.recorder = &MockIPersonRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockIPersonRepository) EXPECT() *MockIPersonRepositoryMockRecorder {
	return _m.recorder
}

// GetPeople mocks base method
func (_m *MockIPersonRepository) GetPeople() ([]domain.Person, *errs.ApiError) {
	ret := _m.ctrl.Call(_m, "GetPeople")
	ret0, _ := ret[0].([]domain.Person)
	ret1, _ := ret[1].(*errs.ApiError)
	return ret0, ret1
}

// GetPeople indicates an expected call of GetPeople
func (_mr *MockIPersonRepositoryMockRecorder) GetPeople() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetPeople", reflect.TypeOf((*MockIPersonRepository)(nil).GetPeople))
}

// CreatePerson mocks base method
func (_m *MockIPersonRepository) CreatePerson(name string) *errs.ApiError {
	ret := _m.ctrl.Call(_m, "CreatePerson", name)
	ret0, _ := ret[0].(*errs.ApiError)
	return ret0
}

// CreatePerson indicates an expected call of CreatePerson
func (_mr *MockIPersonRepositoryMockRecorder) CreatePerson(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CreatePerson", reflect.TypeOf((*MockIPersonRepository)(nil).CreatePerson), arg0)
}

// AddPoints mocks base method
func (_m *MockIPersonRepository) AddPoints(id int, points int) *errs.ApiError {
	ret := _m.ctrl.Call(_m, "AddPoints", id, points)
	ret0, _ := ret[0].(*errs.ApiError)
	return ret0
}

// AddPoints indicates an expected call of AddPoints
func (_mr *MockIPersonRepositoryMockRecorder) AddPoints(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AddPoints", reflect.TypeOf((*MockIPersonRepository)(nil).AddPoints), arg0, arg1)
}

// GetReais mocks base method
func (_m *MockIPersonRepository) GetReais(id int) (int, *errs.ApiError) {
	ret := _m.ctrl.Call(_m, "GetReais", id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(*errs.ApiError)
	return ret0, ret1
}

// GetReais indicates an expected call of GetReais
func (_mr *MockIPersonRepositoryMockRecorder) GetReais(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetReais", reflect.TypeOf((*MockIPersonRepository)(nil).GetReais), arg0)
}

// GetPointsToMessage mocks base method
func (_m *MockIPersonRepository) GetPointsToMessage(id int) (string, *errs.ApiError) {
	ret := _m.ctrl.Call(_m, "GetPointsToMessage", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*errs.ApiError)
	return ret0, ret1
}

// GetPointsToMessage indicates an expected call of GetPointsToMessage
func (_mr *MockIPersonRepositoryMockRecorder) GetPointsToMessage(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetPointsToMessage", reflect.TypeOf((*MockIPersonRepository)(nil).GetPointsToMessage), arg0)
}
